//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int ID_Habitacion { get; set; }
        public Nullable<int> ID_Estado { get; set; }
        public int Extension_Telefonica { get; set; }
        public Nullable<int> ID_Tipo { get; set; }
        public Nullable<int> ID_Hotel { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Tipo_Habitacion Tipo_Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
