//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Huespeds = new HashSet<Huesped>();
        }
    
        public int ID_Reserva { get; set; }
        public Nullable<int> ID_Habitacion { get; set; }
        public Nullable<int> ID_Huesped { get; set; }
        public System.DateTime Fecha_CheckIn { get; set; }
        public System.DateTime Fecha_CheckOut { get; set; }
        public int Cantidad_Adultos { get; set; }
        public int Cantidad_Niños { get; set; }
        public int Huespedes_Adicionales { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Huesped Huesped { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Huesped> Huespeds { get; set; }
    }
}
