//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valores_Generales
    {
        public string Cedula_Juridica { get; set; }
        public string Nombre_Empresa { get; set; }
        public int Impuesto_Venta { get; set; }
        public int Impuesto_Consumo { get; set; }
        public int Impuesto_Servicio { get; set; }
        public string Propietario { get; set; }
        public string Direccion { get; set; }
        public System.TimeSpan Hora_CheckIn { get; set; }
        public System.TimeSpan Hora_CheckOut { get; set; }
    }
}
